-- Consultas OR

/* CHECKLIST 

	SELECT REF 
	SELECT DEREF 
	CONSULTA À VARRAY 
	CONSULTA À NESTED TABLE

*/

-- SELECT REF 

-- SELECT DEREF

-- CONSULTA À VARRAY


-- CONSULTA À NESTED TABLE:

-- SELECIONANDO DEPENDENTE DE UM BIÓLOGO:
SELECT * FROM TABLE (SELECT B.dependentes_de_biologos FROM tb_biologo B WHERE B.cpf = '888.888.888-88');

-- SELECIONANDO DEPENDENTE DE UM ATENDENTE:
SELECT * FROM TABLE (SELECT A.dependentes_de_atendentes FROM tb_atendente A WHERE A.cpf = '202.202.202-20');

-- SELECIONANDO DEPENDENTE DE UM ZELADOR:
SELECT * FROM TABLE (SELECT Z.dependentes_de_zeladores FROM tb_zelador Z WHERE Z.cpf = '606.606.606-60');
